// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApplication6.Backend.Data;

#nullable disable

namespace WebApplication6.Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260920151407_PhotoDisplayCollections")]
    partial class PhotoDisplayCollections
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApplication6.Backend.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<int>("LayoutPreset")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NavTitle")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<int>("NavbarOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(-1);

                    b.Property<bool>("Published")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("NavbarOrder")
                        .IsUnique()
                        .HasDatabaseName("UX_Albums_NavbarOrder_NonNegative")
                        .HasFilter("\"NavbarOrder\" >= 0");

                    b.ToTable("Albums", null, t =>
                        {
                            t.HasCheckConstraint("CK_Albums_NavbarOrder_Range", "\"NavbarOrder\" BETWEEN -1 AND 4");

                            t.HasCheckConstraint("CK_Albums_Unpublished_NoNavbar", "\"Published\" = TRUE OR \"NavbarOrder\" = -1");
                        });
                });

            modelBuilder.Entity("WebApplication6.Backend.Models.AlbumItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlbumId")
                        .HasColumnType("integer");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId", "Order")
                        .IsUnique()
                        .HasDatabaseName("UX_AlbumItems_AlbumId_Order")
                        .HasFilter("\"PhotoDisplayCollectionId\" IS NULL");

                    b.ToTable("AlbumItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_AlbumItems_CollectionItemType", "\"PhotoDisplayCollectionId\" IS NULL OR (\"CollectionItemType\" IS NOT NULL AND \"CollectionItemType\" = 'PhotoDisplayCollection')");

                            t.HasCheckConstraint("CK_AlbumItems_Order_NonNegative", "\"Order\" >= 0");

                            t.HasCheckConstraint("CK_AlbumItems_PhotoDisplayCollection_Mode", "\"ItemType\" <> 'PhotoDisplayCollection' OR (\"DisplayMode\" IS NOT NULL AND \"DisplayMode\" BETWEEN 0 AND 1)");

                            t.HasCheckConstraint("CK_AlbumItems_PhotoDisplay_Columns", "\"ItemType\" = 'PhotoDisplay' OR (\"PhotoId\" IS NULL AND \"PhotoDisplayCollectionId\" IS NULL)");

                            t.HasCheckConstraint("CK_AlbumItems_PhotoDisplay_Required", "\"ItemType\" <> 'PhotoDisplay' OR (\"PhotoId\" IS NOT NULL AND \"DisplaysName\" IS NOT NULL AND \"DisplaysDescription\" IS NOT NULL AND \"DisplaysYearContentCreated\" IS NOT NULL)");
                        });

                    b.HasDiscriminator<string>("ItemType").HasValue("AlbumItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WebApplication6.Backend.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("StorageFileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("WebApplication6.Backend.Models.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ImageId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("YearContentCreated")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("WebApplication6.Backend.Models.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");
                });

            modelBuilder.Entity("WebApplication6.Backend.Models.UntrackedFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<string>("FileStorageLocation")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UntrackedFiles");
                });

            modelBuilder.Entity("WebApplication6.Backend.Models.PhotoDisplay", b =>
                {
                    b.HasBaseType("WebApplication6.Backend.Models.AlbumItem");

                    b.Property<string>("CollectionItemType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("PhotoDisplayCollection");

                    b.Property<bool>("DisplaysDescription")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("DisplaysName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("DisplaysYearContentCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int?>("PhotoDisplayCollectionId")
                        .HasColumnType("integer");

                    b.Property<int>("PhotoId")
                        .HasColumnType("integer");

                    b.HasIndex("PhotoId");

                    b.HasIndex("AlbumId", "PhotoId")
                        .IsUnique()
                        .HasDatabaseName("UX_AlbumItems_AlbumId_PhotoId")
                        .HasFilter("\"ItemType\" = 'PhotoDisplay'");

                    b.HasIndex("PhotoDisplayCollectionId", "Order")
                        .IsUnique()
                        .HasDatabaseName("UX_AlbumItems_PhotoDisplayCollectionId_Order")
                        .HasFilter("\"PhotoDisplayCollectionId\" IS NOT NULL");

                    b.HasIndex("AlbumId", "PhotoDisplayCollectionId", "CollectionItemType");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_AlbumItems_CollectionItemType", "\"PhotoDisplayCollectionId\" IS NULL OR (\"CollectionItemType\" IS NOT NULL AND \"CollectionItemType\" = 'PhotoDisplayCollection')");

                            t.HasCheckConstraint("CK_AlbumItems_Order_NonNegative", "\"Order\" >= 0");

                            t.HasCheckConstraint("CK_AlbumItems_PhotoDisplayCollection_Mode", "\"ItemType\" <> 'PhotoDisplayCollection' OR (\"DisplayMode\" IS NOT NULL AND \"DisplayMode\" BETWEEN 0 AND 1)");

                            t.HasCheckConstraint("CK_AlbumItems_PhotoDisplay_Columns", "\"ItemType\" = 'PhotoDisplay' OR (\"PhotoId\" IS NULL AND \"PhotoDisplayCollectionId\" IS NULL)");

                            t.HasCheckConstraint("CK_AlbumItems_PhotoDisplay_Required", "\"ItemType\" <> 'PhotoDisplay' OR (\"PhotoId\" IS NOT NULL AND \"DisplaysName\" IS NOT NULL AND \"DisplaysDescription\" IS NOT NULL AND \"DisplaysYearContentCreated\" IS NOT NULL)");
                        });

                    b.HasDiscriminator().HasValue("PhotoDisplay");
                });

            modelBuilder.Entity("WebApplication6.Backend.Models.PhotoDisplayCollection", b =>
                {
                    b.HasBaseType("WebApplication6.Backend.Models.AlbumItem");

                    b.Property<int>("DisplayMode")
                        .HasColumnType("integer");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_AlbumItems_CollectionItemType", "\"PhotoDisplayCollectionId\" IS NULL OR (\"CollectionItemType\" IS NOT NULL AND \"CollectionItemType\" = 'PhotoDisplayCollection')");

                            t.HasCheckConstraint("CK_AlbumItems_Order_NonNegative", "\"Order\" >= 0");

                            t.HasCheckConstraint("CK_AlbumItems_PhotoDisplayCollection_Mode", "\"ItemType\" <> 'PhotoDisplayCollection' OR (\"DisplayMode\" IS NOT NULL AND \"DisplayMode\" BETWEEN 0 AND 1)");

                            t.HasCheckConstraint("CK_AlbumItems_PhotoDisplay_Columns", "\"ItemType\" = 'PhotoDisplay' OR (\"PhotoId\" IS NULL AND \"PhotoDisplayCollectionId\" IS NULL)");

                            t.HasCheckConstraint("CK_AlbumItems_PhotoDisplay_Required", "\"ItemType\" <> 'PhotoDisplay' OR (\"PhotoId\" IS NOT NULL AND \"DisplaysName\" IS NOT NULL AND \"DisplaysDescription\" IS NOT NULL AND \"DisplaysYearContentCreated\" IS NOT NULL)");
                        });

                    b.HasDiscriminator().HasValue("PhotoDisplayCollection");
                });

            modelBuilder.Entity("WebApplication6.Backend.Models.AlbumItem", b =>
                {
                    b.HasOne("WebApplication6.Backend.Models.Album", "Album")
                        .WithMany("AlbumItems")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("WebApplication6.Backend.Models.Photo", b =>
                {
                    b.HasOne("WebApplication6.Backend.Models.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("WebApplication6.Backend.Models.PhotoDisplay", b =>
                {
                    b.HasOne("WebApplication6.Backend.Models.Photo", "Photo")
                        .WithMany("PhotoDisplays")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication6.Backend.Models.PhotoDisplayCollection", "PhotoDisplayCollection")
                        .WithMany("PhotoDisplays")
                        .HasForeignKey("AlbumId", "PhotoDisplayCollectionId", "CollectionItemType")
                        .HasPrincipalKey("AlbumId", "Id", "ItemType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_AlbumItems_AlbumItems_AlbumId_CollectionId_ItemType");

                    b.Navigation("Photo");

                    b.Navigation("PhotoDisplayCollection");
                });

            modelBuilder.Entity("WebApplication6.Backend.Models.Album", b =>
                {
                    b.Navigation("AlbumItems");
                });

            modelBuilder.Entity("WebApplication6.Backend.Models.Photo", b =>
                {
                    b.Navigation("PhotoDisplays");
                });

            modelBuilder.Entity("WebApplication6.Backend.Models.PhotoDisplayCollection", b =>
                {
                    b.Navigation("PhotoDisplays");
                });
#pragma warning restore 612, 618
        }
    }
}
